// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package database

import (
	"context"
	"github.com/wesleysnt/framework/contracts/config"
	"github.com/wesleysnt/framework/database/db"
	"github.com/wesleysnt/framework/database/gorm"
)

// Injectors from wire.go:

//go:generate wire
func InitializeOrm(ctx context.Context, config2 config.Config, connection string) (*OrmImpl, error) {
	configImpl := db.NewConfigImpl(config2, connection)
	dialectorImpl := gorm.NewDialectorImpl(config2, connection)
	gormImpl := gorm.NewGormImpl(config2, connection, configImpl, dialectorImpl)
	queryImpl, err := gorm.NewQueryImpl(ctx, config2, gormImpl)
	if err != nil {
		return nil, err
	}
	ormImpl, err := NewOrmImpl(ctx, config2, connection, queryImpl)
	if err != nil {
		return nil, err
	}
	return ormImpl, nil
}
